apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-local-dags-folder
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.hostPath.dags }}
